Evaluation 1


Exercise 1: NumPy array Indexing Slicing


1.1) In this exercise , we will use the iris dataset . Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [1]:
import pandas as pd 
import numpy as np
from si.io.csv_file import read_csv 

df_path = "/home/joao/Portefolio_si/datasets/iris/iris.csv" 
iris_df = read_csv(df_path, sep = ',', features = True, label = True) 
iris_df

In [2]:
iris_df.summary() 

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

1.2) Select the penultimate independent variable . What is the dimension of the resulting array

In [3]:
penultimate_var = iris_df.X[:, -2] 
dim = len(penultimate_var) 
print(f" The dimension of the penultimate independet variable is %d." % dim) 

 The dimension of the penultimate independet variable is 150.



1.3) Select the last 10 samples from the iris dataset . What is the mean of the last 10 samples for each independent variable feature

In [4]:
last_ten = iris_df.X[-10:] 
print(f" The last 10 samples of the dataset are: \n %s" %last_ten) 

 The last 10 samples of the dataset are: 
 [[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [5]:
last_ten_mean = last_ten.mean(axis=0) 
print(f" The mean of each variable of the last 10 samples is: \n %s" %last_ten_mean) #imprime o resultado como uma str

 The mean of each variable of the last 10 samples is: 
 [6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables features . How many samples do you obtain

In [6]:
less6 = iris_df.X[(iris_df.X[:,] <= 6).all(axis=1)]  

In [7]:
print(f" The samples with variables values equal or less 6 are: %s" %len(less6))

 The samples with variables values equal or less 6 are: 89


1.5) Select all samples with a class label different from 'Iris setosa '. How many samples do you obtain

In [8]:
not_setosa_n = iris_df.X[iris_df.y != 'Iris-setosa']
print(f" The samples classified different as Iris setosa are \n %s." %not_setosa_n) 

 The samples classified different as Iris setosa are 
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 

In [9]:
print(f" The number of samples classified different as Iris setosa is %s." %(len(not_setosa_n)))

 The number of samples classified different as Iris setosa is 100.


EXERCISE 2 - Optional: You can add examples of how to use these methods:

dropna
fillna
remove_by_index

In [10]:
from si.data.dataset import Dataset
import numpy as np

dropna

In [11]:
X = np.array([[1, 2, 3],
                   [4, np.nan, 6],
                   [7, 8, 9]])

y = np.array([10, 11, 12])
features = ['A', 'B', 'C']
label = ['y']
data = Dataset(X, y, features, label)

print("Before dropna:\n", data.X)
data.dropna()
print("After dropna:\n", data.X)

Before dropna:
 [[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
After dropna:
 [[1. 2. 3.]
 [7. 8. 9.]]


fillna

In [12]:
X = np.array([[1, 2, 3],
                   [4, np.nan, 6],
                   [7, 8, 9]])

y = np.array([10, 11, 12])
features = ['A', 'B', 'C']
label = ['y']

data = Dataset(X, y, features, label)
print("Before fillna:\n", data.X)
data.fillna(1)
print("After fillna float:\n",data.X)

data = Dataset(X, y, features, label)
data.fillna('mean')
print("After fillna mean:\n", data.X)

data = Dataset(X, y, features, label)
data.fillna('median')
print("After fillna median:\n", data.X)

Before fillna:
 [[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
After fillna float:
 [[1. 2. 3.]
 [4. 1. 6.]
 [7. 8. 9.]]
After fillna mean:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
After fillna median:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


remove_by_index

In [13]:
X = np.array([[1, 2, 3],
                   [4, np.nan, 6],
                   [7, 8, 9]])

y = np.array([10, 11, 12])
features = ['A', 'B', 'C']
label = ['y']

data = Dataset(X, y, features, label)
print(data.X)
print()
data.remove_by_index(1)
print(data.X)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]

[[1. 2. 3.]
 [7. 8. 9.]]
